sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
language: python
python:
    - "3.4"
install:
    - pip install -e .[development]
script:
    - pylint serverstf
    - docker build --tag serverstf:latest .
after_success:
  - docker-push.sh
