sudo: required
services:
  - docker
language: python
python:
    - "3.4"
install:
    - pip install -e .[development]
    - npm install
    - node_modules/.bin/bower install
script:
    - node_modules/.bin/grunt
    - pylint serverstf
    - docker build --tag serverstf:latest .
