language: python
python:
    - "3.4"
install:
    - pip install -e .[development]
    - npm install
    - node_modules/.bin/bower install
script:
    - serverstf --help
    - serverstf poll --help
    - serverstf poller --help
    - serverstf ui --help
    - serverstf sync --help
    - serverstf latency --help
    - serverstf latency-curve --help
    - serverstf latency-plot --help
    - serverstf websocket --help
    - node_modules/.bin/grunt
    - pylint serverstf
